services:
  - type: web
    name: tikfinity-gift-overlay
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
